### PR TITLE
Check captcha only if site/secret keys are set

### PR DESCRIPTION
**Pull request by getdatakick**
If Site or Secret key is not set, the call to cloudflare api would fail anyway.

### CODE REVIEW

**Comment by eschiendorfer** [comment]
Thanks a lot! Yes I was actually aware of it. The other issue is actually related to this one :) I will look at your code changes at home and then merge it. 
Btw are you using this module?

**Comment by getdatakick** [comment]
Great. 

I personally do not use it, but one of my clients do. We are trying to clean up their error logs as a preparation for PHP8.2 update

**Comment by eschiendorfer** [comment]
Can you shortly explain why confix.xml is needed? Isn't this file generated automatically? All this informations should match the information in the construct method, right?

**Comment by getdatakick** [comment]
It's not needed. But since you have this file committed to the repository, I've changed is as well, so it's in sync.

I suggest you create `.gitignore` file to exclude this file from git repository, and then delete config.xml completely.

**Comment by eschiendorfer** [comment]
Hm I kind of confused, cause the PR adds the file config.xml. Am I missing something?

**Comment by getdatakick** [comment]
right, my bad

**Comment by getdatakick** [comment]
See new version with `.gitignore` file

**Pull request merged**
